### ISSUE TITLE
FPP Plugin Instability on Pi 5

### ISSUE THREAD

**Issue by rdkbob** [PulseMeshLabs/pulsemesh-openbeta#11]

**Comment by JobyB** [comment]
Since I updated to FPP 8.2 and PulseMash 1.0.34 its been stable for 48 hours :) will keep reporting in.

**Comment by rdkbob** [comment]
@JobyB - just checking in, any further issues?

**Comment by JobyB** [comment]
Nope, all good, been checking it every day, it's been rock solid since the last update, thanks!

**Comment by rdkbob** [comment]
Thanks!  Closing this issue for now, feel free to reopen if needed.
