### ISSUE TITLE
Audio pauses on device rotation

### ISSUE THREAD

**Issue by jlinburg** [PulseMeshLabs/pulsemesh-openbeta#12]
On my Pixel 6 Pro running Android 14, the audio will pause and resync whenever the device screen auto-rotates. 
Simple solution would be to hard set rotation to portrait in AndroidManifest.xml  android:screenOrientation="portrait"

**Comment by rdkbob** [comment]
Thanks for the feedback!  I'll try to repro this and add a fix.  Right now the screen orientation lock would be a fine fix, but for some planned future features that may be limiting.

**Comment by rdkbob** [comment]
I was able to replicate this on a Pixel 6a.  Planning to go forward with the locked orientation on Android for now and revisit in the future if rotation is needed.  Fix planned for 1.0.3 on Android.

**Comment by rdkbob** [comment]
Closing as this is now released on both iOS and Android.
